### ISSUE TITLE
Artisul D16 Pro Diagnostics

### ISSUE THREAD

**Issue by WanderingFeral** [DIGImend/digimend-kernel-drivers#482]
Tablet manufacturer: Artisul (looks like a UC-Logic re-brand)
Model name: D15 Pro
Purchased from: https://www.artisul.com/store/55-26-D16-Pro.html#/29-warehouse-eu

Diagnostics:

[descriptors.txt](https://github.com/DIGImend/digimend-kernel-drivers/files/5560784/descriptors.txt)
[frame_buttons.txt](https://github.com/DIGImend/digimend-kernel-drivers/files/5560785/frame_buttons.txt)
[frame_dials.txt](https://github.com/DIGImend/digimend-kernel-drivers/files/5560786/frame_dials.txt)
[hid_report_descriptors.txt](https://github.com/DIGImend/digimend-kernel-drivers/files/5560787/hid_report_descriptors.txt)
[pen_buttons.txt](https://github.com/DIGImend/digimend-kernel-drivers/files/5560788/pen_buttons.txt)
[pen_coords.txt](https://github.com/DIGImend/digimend-kernel-drivers/files/5560789/pen_coords.txt)
[pen_pressure.txt](https://github.com/DIGImend/digimend-kernel-drivers/files/5560791/pen_pressure.txt)
[pen_tilt.txt](https://github.com/DIGImend/digimend-kernel-drivers/files/5560792/pen_tilt.txt)
[probe.txt](https://github.com/DIGImend/digimend-kernel-drivers/files/5560793/probe.txt)

The stylus works (just have to map it to the built-in screen) but the buttons don't. Is there any way to get them working temporarily?

**Comment by WanderingFeral** [comment]
I have been doing some digging around and have found the following:

/sys/kernel/debug/hid/0003:256C:006D.000E/events (Dial and button) returns:

```
report (size 9) (numbered) =  10 00 32 00 00 00 00 00 00
Button.0001 = 0
Digitizers.Touch = 0
GenericDesktop.Dial = 50
GenericDesktop.X = 0
GenericDesktop.Y = 0
Digitizers.Width = 0

report (size 9) (numbered) =  10 00 32 00 00 00 00 00 00
Button.0001 = 0
Digitizers.Touch = 0
GenericDesktop.Dial = 50
GenericDesktop.X = 0
GenericDesktop.Y = 0
Digitizers.Width = 0

report (size 9) (numbered) =  10 00 32 00 00 00 00 00 00
Button.0001 = 0
Digitizers.Touch = 0
GenericDesktop.Dial = 50
GenericDesktop.X = 0
GenericDesktop.Y = 0
Digitizers.Width = 0

report (size 9) (numbered) =  10 00 32 00 00 00 00 00 00
Button.0001 = 0
Digitizers.Touch = 0
GenericDesktop.Dial = 50
GenericDesktop.X = 0
GenericDesktop.Y = 0
Digitizers.Width = 0

report (size 9) (numbered) =  10 00 32 00 00 00 00 00 00
Button.0001 = 0
Digitizers.Touch = 0
GenericDesktop.Dial = 50
GenericDesktop.X = 0
GenericDesktop.Y = 0
Digitizers.Width = 0

report (size 9) (numbered) =  10 00 32 00 00 00 00 00 00
Button.0001 = 0
Digitizers.Touch = 0
GenericDesktop.Dial = 50
GenericDesktop.X = 0
GenericDesktop.Y = 0
Digitizers.Width = 0

report (size 9) (numbered) =  10 00 32 00 00 00 00 00 00
Button.0001 = 0
Digitizers.Touch = 0
GenericDesktop.Dial = 50
GenericDesktop.X = 0
GenericDesktop.Y = 0
Digitizers.Width = 0

report (size 9) (numbered) =  10 00 32 00 00 00 00 00 00
Button.0001 = 0
Digitizers.Touch = 0
GenericDesktop.Dial = 50
GenericDesktop.X = 0
GenericDesktop.Y = 0
Digitizers.Width = 0

report (size 9) (numbered) =  10 00 ce ff 00 00 00 00 00
Button.0001 = 0
Digitizers.Touch = 0
GenericDesktop.Dial = -50
GenericDesktop.X = 0
GenericDesktop.Y = 0
Digitizers.Width = 0

report (size 9) (numbered) =  10 00 ce ff 00 00 00 00 00
Button.0001 = 0
Digitizers.Touch = 0
GenericDesktop.Dial = -50
GenericDesktop.X = 0
GenericDesktop.Y = 0
Digitizers.Width = 0

report (size 9) (numbered) =  10 00 ce ff 00 00 00 00 00
Button.0001 = 0
Digitizers.Touch = 0
GenericDesktop.Dial = -50
GenericDesktop.X = 0
GenericDesktop.Y = 0
Digitizers.Width = 0

report (size 9) (numbered) =  10 00 ce ff 00 00 00 00 00
Button.0001 = 0
Digitizers.Touch = 0
GenericDesktop.Dial = -50
GenericDesktop.X = 0
GenericDesktop.Y = 0
Digitizers.Width = 0

report (size 9) (numbered) =  10 00 ce ff 00 00 00 00 00
Button.0001 = 0
Digitizers.Touch = 0
GenericDesktop.Dial = -50
GenericDesktop.X = 0
GenericDesktop.Y = 0
Digitizers.Width = 0

report (size 9) (numbered) =  10 00 ce ff 00 00 00 00 00
Button.0001 = 0
Digitizers.Touch = 0
GenericDesktop.Dial = -50
GenericDesktop.X = 0
GenericDesktop.Y = 0
Digitizers.Width = 0

report (size 9) (numbered) =  10 00 ce ff 00 00 00 00 00
Button.0001 = 0
Digitizers.Touch = 0
GenericDesktop.Dial = -50
GenericDesktop.X = 0
GenericDesktop.Y = 0
Digitizers.Width = 0

report (size 9) (numbered) =  10 00 ce ff 00 00 00 00 00
Button.0001 = 0
Digitizers.Touch = 0
GenericDesktop.Dial = -50
GenericDesktop.X = 0
GenericDesktop.Y = 0
Digitizers.Width = 0

report (size 9) (numbered) =  10 00 ce ff 00 00 00 00 00
Button.0001 = 0
Digitizers.Touch = 0
GenericDesktop.Dial = -50
GenericDesktop.X = 0
GenericDesktop.Y = 0
Digitizers.Width = 0

report (size 9) (numbered) =  10 00 ce ff 00 00 00 00 00
Button.0001 = 0
Digitizers.Touch = 0
GenericDesktop.Dial = -50
GenericDesktop.X = 0
GenericDesktop.Y = 0
Digitizers.Width = 0

report (size 9) (numbered) =  10 00 ce ff 00 00 00 00 00
Button.0001 = 0
Digitizers.Touch = 0
GenericDesktop.Dial = -50
GenericDesktop.X = 0
GenericDesktop.Y = 0
Digitizers.Width = 0

report (size 9) (numbered) =  10 00 ce ff 00 00 00 00 00
Button.0001 = 0
Digitizers.Touch = 0
GenericDesktop.Dial = -50
GenericDesktop.X = 0
GenericDesktop.Y = 0
Digitizers.Width = 0

report (size 9) (numbered) =  10 00 ce ff 00 00 00 00 00
Button.0001 = 0
Digitizers.Touch = 0
GenericDesktop.Dial = -50
GenericDesktop.X = 0
GenericDesktop.Y = 0
Digitizers.Width = 0

report (size 9) (numbered) =  10 00 ce ff 00 00 00 00 00
Button.0001 = 0
Digitizers.Touch = 0
GenericDesktop.Dial = -50
GenericDesktop.X = 0
GenericDesktop.Y = 0
Digitizers.Width = 0

report (size 9) (numbered) =  10 00 32 00 00 00 00 00 00
Button.0001 = 0
Digitizers.Touch = 0
GenericDesktop.Dial = 50
GenericDesktop.X = 0
GenericDesktop.Y = 0
Digitizers.Width = 0

report (size 9) (numbered) =  10 00 32 00 00 00 00 00 00
Button.0001 = 0
Digitizers.Touch = 0
GenericDesktop.Dial = 50
GenericDesktop.X = 0
GenericDesktop.Y = 0
Digitizers.Width = 0

report (size 9) (numbered) =  10 00 32 00 00 00 00 00 00
Button.0001 = 0
Digitizers.Touch = 0
GenericDesktop.Dial = 50
GenericDesktop.X = 0
GenericDesktop.Y = 0
Digitizers.Width = 0

report (size 9) (numbered) =  10 00 32 00 00 00 00 00 00
Button.0001 = 0
Digitizers.Touch = 0
GenericDesktop.Dial = 50
GenericDesktop.X = 0
GenericDesktop.Y = 0
Digitizers.Width = 0

report (size 9) (numbered) =  10 00 32 00 00 00 00 00 00
Button.0001 = 0
Digitizers.Touch = 0
GenericDesktop.Dial = 50
GenericDesktop.X = 0
GenericDesktop.Y = 0
Digitizers.Width = 0

report (size 9) (numbered) =  10 00 32 00 00 00 00 00 00
Button.0001 = 0
Digitizers.Touch = 0
GenericDesktop.Dial = 50
GenericDesktop.X = 0
GenericDesktop.Y = 0
Digitizers.Width = 0

report (size 9) (numbered) =  10 00 32 00 00 00 00 00 00
Button.0001 = 0
Digitizers.Touch = 0
GenericDesktop.Dial = 50
GenericDesktop.X = 0
GenericDesktop.Y = 0
Digitizers.Width = 0

report (size 9) (numbered) =  10 00 32 00 00 00 00 00 00
Button.0001 = 0
Digitizers.Touch = 0
GenericDesktop.Dial = 50
GenericDesktop.X = 0
GenericDesktop.Y = 0
Digitizers.Width = 0

report (size 9) (numbered) =  10 00 32 00 00 00 00 00 00
Button.0001 = 0
Digitizers.Touch = 0
GenericDesktop.Dial = 50
GenericDesktop.X = 0
GenericDesktop.Y = 0
Digitizers.Width = 0

report (size 9) (numbered) =  10 00 32 00 00 00 00 00 00
Button.0001 = 0
Digitizers.Touch = 0
GenericDesktop.Dial = 50
GenericDesktop.X = 0
GenericDesktop.Y = 0
Digitizers.Width = 0

report (size 9) (numbered) =  10 00 32 00 00 00 00 00 00
Button.0001 = 0
Digitizers.Touch = 0
GenericDesktop.Dial = 50
GenericDesktop.X = 0
GenericDesktop.Y = 0
Digitizers.Width = 0

report (size 9) (numbered) =  10 01 00 00 00 00 00 00 00
Button.0001 = 1
Digitizers.Touch = 0
GenericDesktop.Dial = 0
GenericDesktop.X = 0
GenericDesktop.Y = 0
Digitizers.Width = 0

report (size 9) (numbered) =  10 00 00 00 00 00 00 00 00
Button.0001 = 0
Digitizers.Touch = 0
GenericDesktop.Dial = 0
GenericDesktop.X = 0
GenericDesktop.Y = 0
Digitizers.Width = 0

report (size 9) (numbered) =  10 01 00 00 00 00 00 00 00
Button.0001 = 1
Digitizers.Touch = 0
GenericDesktop.Dial = 0
GenericDesktop.X = 0
GenericDesktop.Y = 0
Digitizers.Width = 0

report (size 9) (numbered) =  10 00 00 00 00 00 00 00 00
Button.0001 = 0
Digitizers.Touch = 0
GenericDesktop.Dial = 0
GenericDesktop.X = 0
GenericDesktop.Y = 0
Digitizers.Width = 0
```
/sys/kernel/debug/hid/0003:256C:006D.000C/events (Buttons) returns:

```
report (size 12) (numbered) =  08 e0 01 01 01 00 00 00 00 00 00 00
Digitizers.BarrelSwitch = 0
GenericDesktop.X = 0
GenericDesktop.Y = 0
Button.0001 = 1
Button.0002 = 0
Button.0003 = 0
Button.0004 = 0
Button.0005 = 0
Button.0006 = 0
Button.0007 = 0
Button.0008 = 0
Button.0009 = 0
Button.000a = 0
Button.0001 = 0
Button.0002 = 0

report (size 12) (numbered) =  08 e0 01 01 00 00 00 00 00 00 00 00
Digitizers.BarrelSwitch = 0
GenericDesktop.X = 0
GenericDesktop.Y = 0
Button.0001 = 0
Button.0002 = 0
Button.0003 = 0
Button.0004 = 0
Button.0005 = 0
Button.0006 = 0
Button.0007 = 0
Button.0008 = 0
Button.0009 = 0
Button.000a = 0
Button.0001 = 0
Button.0002 = 0

report (size 12) (numbered) =  08 e0 01 01 02 00 00 00 00 00 00 00
Digitizers.BarrelSwitch = 0
GenericDesktop.X = 0
GenericDesktop.Y = 0
Button.0001 = 0
Button.0002 = 1
Button.0003 = 0
Button.0004 = 0
Button.0005 = 0
Button.0006 = 0
Button.0007 = 0
Button.0008 = 0
Button.0009 = 0
Button.000a = 0
Button.0001 = 0
Button.0002 = 0

report (size 12) (numbered) =  08 e0 01 01 00 00 00 00 00 00 00 00
Digitizers.BarrelSwitch = 0
GenericDesktop.X = 0
GenericDesktop.Y = 0
Button.0001 = 0
Button.0002 = 0
Button.0003 = 0
Button.0004 = 0
Button.0005 = 0
Button.0006 = 0
Button.0007 = 0
Button.0008 = 0
Button.0009 = 0
Button.000a = 0
Button.0001 = 0
Button.0002 = 0

report (size 12) (numbered) =  08 e0 01 01 04 00 00 00 00 00 00 00
Digitizers.BarrelSwitch = 0
GenericDesktop.X = 0
GenericDesktop.Y = 0
Button.0001 = 0
Button.0002 = 0
Button.0003 = 1
Button.0004 = 0
Button.0005 = 0
Button.0006 = 0
Button.0007 = 0
Button.0008 = 0
Button.0009 = 0
Button.000a = 0
Button.0001 = 0
Button.0002 = 0

report (size 12) (numbered) =  08 e0 01 01 00 00 00 00 00 00 00 00
Digitizers.BarrelSwitch = 0
GenericDesktop.X = 0
GenericDesktop.Y = 0
Button.0001 = 0
Button.0002 = 0
Button.0003 = 0
Button.0004 = 0
Button.0005 = 0
Button.0006 = 0
Button.0007 = 0
Button.0008 = 0
Button.0009 = 0
Button.000a = 0
Button.0001 = 0
Button.0002 = 0

report (size 12) (numbered) =  08 e0 01 01 08 00 00 00 00 00 00 00
Digitizers.BarrelSwitch = 0
GenericDesktop.X = 0
GenericDesktop.Y = 0
Button.0001 = 0
Button.0002 = 0
Button.0003 = 0
Button.0004 = 1
Button.0005 = 0
Button.0006 = 0
Button.0007 = 0
Button.0008 = 0
Button.0009 = 0
Button.000a = 0
Button.0001 = 0
Button.0002 = 0

report (size 12) (numbered) =  08 e0 01 01 00 00 00 00 00 00 00 00
Digitizers.BarrelSwitch = 0
GenericDesktop.X = 0
GenericDesktop.Y = 0
Button.0001 = 0
Button.0002 = 0
Button.0003 = 0
Button.0004 = 0
Button.0005 = 0
Button.0006 = 0
Button.0007 = 0
Button.0008 = 0
Button.0009 = 0
Button.000a = 0
Button.0001 = 0
Button.0002 = 0

report (size 12) (numbered) =  08 e0 01 01 10 00 00 00 00 00 00 00
Digitizers.BarrelSwitch = 0
GenericDesktop.X = 0
GenericDesktop.Y = 0
Button.0001 = 0
Button.0002 = 0
Button.0003 = 0
Button.0004 = 0
Button.0005 = 1
Button.0006 = 0
Button.0007 = 0
Button.0008 = 0
Button.0009 = 0
Button.000a = 0
Button.0001 = 0
Button.0002 = 0

report (size 12) (numbered) =  08 e0 01 01 00 00 00 00 00 00 00 00
Digitizers.BarrelSwitch = 0
GenericDesktop.X = 0
GenericDesktop.Y = 0
Button.0001 = 0
Button.0002 = 0
Button.0003 = 0
Button.0004 = 0
Button.0005 = 0
Button.0006 = 0
Button.0007 = 0
Button.0008 = 0
Button.0009 = 0
Button.000a = 0
Button.0001 = 0
Button.0002 = 0

report (size 12) (numbered) =  08 e0 01 01 20 00 00 00 00 00 00 00
Digitizers.BarrelSwitch = 0
GenericDesktop.X = 0
GenericDesktop.Y = 0
Button.0001 = 0
Button.0002 = 0
Button.0003 = 0
Button.0004 = 0
Button.0005 = 0
Button.0006 = 1
Button.0007 = 0
Button.0008 = 0
Button.0009 = 0
Button.000a = 0
Button.0001 = 0
Button.0002 = 0

report (size 12) (numbered) =  08 e0 01 01 00 00 00 00 00 00 00 00
Digitizers.BarrelSwitch = 0
GenericDesktop.X = 0
GenericDesktop.Y = 0
Button.0001 = 0
Button.0002 = 0
Button.0003 = 0
Button.0004 = 0
Button.0005 = 0
Button.0006 = 0
Button.0007 = 0
Button.0008 = 0
Button.0009 = 0
Button.000a = 0
Button.0001 = 0
Button.0002 = 0

report (size 12) (numbered) =  08 e0 01 01 40 00 00 00 00 00 00 00
Digitizers.BarrelSwitch = 0
GenericDesktop.X = 0
GenericDesktop.Y = 0
Button.0001 = 0
Button.0002 = 0
Button.0003 = 0
Button.0004 = 0
Button.0005 = 0
Button.0006 = 0
Button.0007 = 1
Button.0008 = 0
Button.0009 = 0
Button.000a = 0
Button.0001 = 0
Button.0002 = 0

report (size 12) (numbered) =  08 e0 01 01 00 00 00 00 00 00 00 00
Digitizers.BarrelSwitch = 0
GenericDesktop.X = 0
GenericDesktop.Y = 0
Button.0001 = 0
Button.0002 = 0
Button.0003 = 0
Button.0004 = 0
Button.0005 = 0
Button.0006 = 0
Button.0007 = 0
Button.0008 = 0
Button.0009 = 0
Button.000a = 0
Button.0001 = 0
Button.0002 = 0

```

**Comment by WanderingFeral** [comment]
libinput record (/dev/input/event16:	UC-Logic ARTISUL D16Pro Pad) returns:

```
Select the device event number: 16
Recording to 'stdout'.
version: 1
ndevices: 1
libinput:
  version: "1.16.3"
  git: "unknown"
system:
  kernel: "5.9.9-arch1-1"
  dmi: "dmi:bvnInsydeCorp.:bvrV1.12:bd08/02/2016:br0.0:efr2.10:svnAcer:pnAspireE5-575:pvrV1.12:rvnAcer:rnIronman_SK:rvrV1.12:cvnChassisManufacturer:ct10:cvrChassisVersion:"
devices:
- node: /dev/input/event16
  evdev:
    # Name: UC-Logic ARTISUL D16Pro Pad
    # ID: bus 0x3 vendor 0x256c product 0x6d version 0x111
    # Size in mm: unknown, missing resolution
    # Supported Events:
    # Event type 0 (EV_SYN)
    # Event type 1 (EV_KEY)
    #   Event code 256 (BTN_0)
    #   Event code 257 (BTN_1)
    #   Event code 258 (BTN_2)
    #   Event code 259 (BTN_3)
    #   Event code 260 (BTN_4)
    #   Event code 261 (BTN_5)
    #   Event code 262 (BTN_6)
    #   Event code 263 (BTN_7)
    #   Event code 264 (BTN_8)
    #   Event code 265 (BTN_9)
    #   Event code 304 (BTN_SOUTH)
    #   Event code 305 (BTN_EAST)
    #   Event code 331 (BTN_STYLUS)
    # Event type 3 (EV_ABS)
    #   Event code 0 (ABS_X)
    #       Value           0
    #       Min             0
    #       Max             1
    #       Fuzz            0
    #       Flat            0
    #       Resolution      0
    #   Event code 1 (ABS_Y)
    #       Value           0
    #       Min             0
    #       Max             1
    #       Fuzz            0
    #       Flat            0
    #       Resolution      0
    # Event type 4 (EV_MSC)
    #   Event code 4 (MSC_SCAN)
    # Properties:
    name: "UC-Logic ARTISUL D16Pro Pad"
    id: [3, 9580, 109, 273]
    codes:
      0: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15] # EV_SYN
      1: [256, 257, 258, 259, 260, 261, 262, 263, 264, 265, 304, 305, 331] # EV_KEY
      3: [0, 1] # EV_ABS
      4: [4] # EV_MSC
    absinfo:
      0: [0, 1, 0, 0, 0]
      1: [0, 1, 0, 0, 0]
    properties: []
  hid: [5, 13, 9, 2, 161, 1, 133, 8, 9, 32, 160, 20, 37, 1, 117, 1, 9, 66, 9, 68, 9, 70, 149, 3, 129, 2, 149, 3, 129, 3, 9, 50, 149, 1, 129, 2, 149, 1, 129, 3, 149, 1, 164, 5, 1, 101, 19, 85, 253, 117, 24, 52, 9, 48, 39, 226, 12, 1, 0, 71, 238, 52, 0, 0, 129, 2, 9, 49, 39, 58, 151, 0, 0, 71, 196, 29, 0, 0, 129, 2, 180, 9, 48, 117, 16, 39, 255, 31, 0, 0, 129, 2, 129, 3, 192, 192, 5, 1, 9, 7, 161, 1, 133, 247, 20, 37, 1, 117, 1, 5, 13, 9, 57, 160, 9, 68, 149, 1, 129, 2, 5, 1, 9, 48, 9, 49, 149, 2, 129, 2, 149, 21, 129, 1, 5, 9, 25, 1, 41, 10, 149, 10, 129, 2, 192, 5, 1, 9, 5, 160, 5, 9, 25, 1, 41, 2, 149, 2, 129, 2, 149, 52, 129, 1, 192, 192 ]
  udev:
    properties:
    - ID_INPUT=1
    - ID_INPUT_TABLET=1
    - ID_INPUT_TABLET_PAD=1
    - LIBINPUT_DEVICE_GROUP=3/256c/6d:usb-0000:00:14.0-2.4
  quirks:
  events:
  - evdev:
    - [  0,      0,   4,   4,      30] # EV_MSC / MSC_SCAN                 30 (obfuscated)
  - evdev:
    - [  0,      0,   1, 256,       1] # EV_KEY / BTN_0                     1
    - [  0,      0,   0,   0,       0] # ------------ SYN_REPORT (0) ---------- +0ms
  - evdev:
    - [  0, 153923,   4,   4,      30] # EV_MSC / MSC_SCAN                 30 (obfuscated)
    - [  0, 153923,   1, 256,       0] # EV_KEY / BTN_0                     0
    - [  0, 153923,   0,   0,       0] # ------------ SYN_REPORT (0) ---------- +153ms

```

libinput record (/dev/input/event21:	UC-Logic ARTISUL D16Pro) returns: 

```
Select the device event number: 21
Recording to 'stdout'.
version: 1
ndevices: 1
libinput:
  version: "1.16.3"
  git: "unknown"
system:
  kernel: "5.9.9-arch1-1"
  dmi: "dmi:bvnInsydeCorp.:bvrV1.12:bd08/02/2016:br0.0:efr2.10:svnAcer:pnAspireE5-575:pvrV1.12:rvnAcer:rnIronman_SK:rvrV1.12:cvnChassisManufacturer:ct10:cvrChassisVersion:"
devices:
- node: /dev/input/event21
  evdev:
    # Name: UC-Logic ARTISUL D16Pro
    # ID: bus 0x3 vendor 0x256c product 0x6d version 0x111
    # Size in mm: unknown, missing resolution
    # Supported Events:
    # Event type 0 (EV_SYN)
    # Event type 1 (EV_KEY)
    #   Event code 256 (BTN_0)
    #   Event code 330 (BTN_TOUCH)
    # Event type 2 (EV_REL)
    #   Event code 7 (REL_DIAL)
    # Event type 3 (EV_ABS)
    #   Event code 0 (ABS_X)
    #       Value           0
    #       Min             0
    #       Max             0
    #       Fuzz            0
    #       Flat            0
    #       Resolution      0
    #   Event code 1 (ABS_Y)
    #       Value           0
    #       Min             0
    #       Max             0
    #       Fuzz            0
    #       Flat            0
    #       Resolution      0
    # Event type 4 (EV_MSC)
    #   Event code 4 (MSC_SCAN)
    # Properties:
    name: "UC-Logic ARTISUL D16Pro"
    id: [3, 9580, 109, 273]
    codes:
      0: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15] # EV_SYN
      1: [256, 330] # EV_KEY
      2: [7] # EV_REL
      3: [0, 1] # EV_ABS
      4: [4] # EV_MSC
    absinfo:
      0: [0, 0, 0, 0, 0]
      1: [0, 0, 0, 0, 0]
    properties: []
  hid: [5, 1, 9, 6, 161, 1, 133, 3, 5, 7, 25, 224, 41, 231, 21, 0, 37, 1, 117, 1, 149, 8, 129, 2, 5, 7, 25, 0, 41, 255, 38, 255, 0, 117, 8, 149, 6, 129, 0, 192, 5, 12, 9, 1, 161, 1, 133, 4, 25, 0, 42, 60, 2, 21, 0, 38, 60, 2, 149, 1, 117, 16, 129, 0, 192, 5, 1, 9, 128, 161, 1, 133, 5, 25, 129, 41, 131, 21, 0, 37, 1, 117, 1, 149, 3, 129, 2, 149, 5, 129, 1, 192, 5, 1, 9, 14, 161, 1, 133, 16, 5, 13, 9, 33, 161, 2, 21, 0, 37, 1, 117, 1, 149, 1, 161, 0, 5, 9, 9, 1, 129, 2, 5, 13, 9, 51, 129, 2, 149, 6, 129, 3, 161, 2, 5, 1, 9, 55, 22, 0, 128, 38, 255, 127, 117, 16, 149, 1, 129, 6, 53, 0, 70, 16, 14, 21, 0, 38, 16, 14, 9, 72, 177, 2, 69, 0, 192, 85, 14, 101, 17, 70, 0, 0, 38, 0, 0, 9, 48, 129, 66, 9, 49, 70, 0, 0, 38, 0, 0, 129, 66, 5, 13, 9, 72, 21, 58, 37, 58, 117, 8, 85, 15, 53, 58, 69, 58, 129, 3, 85, 0, 101, 0, 53, 0, 69, 0, 5, 14, 9, 1, 161, 2, 21, 0, 38, 255, 0, 9, 36, 177, 66, 9, 36, 145, 66, 21, 1, 37, 7, 9, 32, 177, 66, 9, 33, 145, 66, 37, 10, 9, 40, 177, 66, 117, 16, 38, 208, 7, 9, 37, 177, 66, 9, 37, 145, 66, 192, 192, 192, 192 ]
  udev:
    properties:
    - ID_INPUT=1
    - ID_INPUT_TABLET=1
    - ID_INPUT_TOUCHSCREEN=1
    - LIBINPUT_DEVICE_GROUP=3/256c/6d:usb-0000:00:14.0-2.4
  quirks:
  events:
  - evdev:
    - [  0,      0,   2,   7,      50] # EV_REL / REL_DIAL                 50
  - evdev:
    - [  0,      0,   0,   0,       0] # ------------ SYN_REPORT (0) ---------- +0ms
  - evdev:
    - [  0,  67868,   2,   7,      50] # EV_REL / REL_DIAL                 50
    - [  0,  67868,   0,   0,       0] # ------------ SYN_REPORT (0) ---------- +67ms
  - evdev:
    - [  0, 115937,   2,   7,      50] # EV_REL / REL_DIAL                 50
    - [  0, 115937,   0,   0,       0] # ------------ SYN_REPORT (0) ---------- +48ms
  - evdev:
    - [  0, 223938,   2,   7,      50] # EV_REL / REL_DIAL                 50
    - [  0, 223938,   0,   0,       0] # ------------ SYN_REPORT (0) ---------- +108ms
  - evdev:
    - [  0, 291931,   2,   7,      50] # EV_REL / REL_DIAL                 50
    - [  0, 291931,   0,   0,       0] # ------------ SYN_REPORT (0) ---------- +68ms
  - evdev:
    - [  0, 363945,   2,   7,      50] # EV_REL / REL_DIAL                 50
    - [  0, 363945,   0,   0,       0] # ------------ SYN_REPORT (0) ---------- +72ms
  - evdev:
    - [  0, 504005,   2,   7,      50] # EV_REL / REL_DIAL                 50
    - [  0, 504005,   0,   0,       0] # ------------ SYN_REPORT (0) ---------- +141ms
  - evdev:
    - [  1, 396020,   4,   4,      30] # EV_MSC / MSC_SCAN                 30 (obfuscated)
    - [  1, 396020,   1, 256,       1] # EV_KEY / BTN_0                     1
    - [  1, 396020,   0,   0,       0] # ------------ SYN_REPORT (0) ---------- +892ms
  - evdev:
    - [  1, 667854,   4,   4,      30] # EV_MSC / MSC_SCAN                 30 (obfuscated)
    - [  1, 667854,   1, 256,       0] # EV_KEY / BTN_0                     0
    - [  1, 667854,   0,   0,       0] # ------------ SYN_REPORT (0) ---------- +271ms
  - evdev:
    - [  3, 311788,   2,   7,     -50] # EV_REL / REL_DIAL                -50
    - [  3, 311788,   0,   0,       0] # ------------ SYN_REPORT (0) ---------- +1644ms
  - evdev:
    - [  3, 347868,   2,   7,     -50] # EV_REL / REL_DIAL                -50
    - [  3, 347868,   0,   0,       0] # ------------ SYN_REPORT (0) ---------- +36ms
  - evdev:
    - [  3, 471979,   2,   7,     -50] # EV_REL / REL_DIAL                -50
    - [  3, 471979,   0,   0,       0] # ------------ SYN_REPORT (0) ---------- +124ms
  - evdev:
    - [  3, 535955,   2,   7,     -50] # EV_REL / REL_DIAL                -50
    - [  3, 535955,   0,   0,       0] # ------------ SYN_REPORT (0) ---------- +64ms
  - evdev:
    - [  3, 704004,   2,   7,     -50] # EV_REL / REL_DIAL                -50
    - [  3, 704004,   0,   0,       0] # ------------ SYN_REPORT (0) ---------- +169ms
  - evdev:
    - [  4, 159842,   4,   4,      30] # EV_MSC / MSC_SCAN                 30 (obfuscated)
    - [  4, 159842,   1, 256,       1] # EV_KEY / BTN_0                     1
    - [  4, 159842,   0,   0,       0] # ------------ SYN_REPORT (0) ---------- +455ms
  - evdev:
    - [  4, 299953,   4,   4,      30] # EV_MSC / MSC_SCAN                 30 (obfuscated)
    - [  4, 299953,   1, 256,       0] # EV_KEY / BTN_0                     0
    - [  4, 299953,   0,   0,       0] # ------------ SYN_REPORT (0) ---------- +140ms

```
